/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package POS.Forms;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.Timer;

/**
 *
 * @author 91027751
 */
public class POSFrame extends javax.swing.JFrame{
int accessLevel;
        DefaultListModel productListModel = new DefaultListModel();
        DefaultListModel priceListModel = new DefaultListModel();
        double totalPrice;
        boolean transactionAuthorised = false;
        int codeOnHold;
    /**
     * Creates new form NewJFrame
     * @param UserName
     */
    public POSFrame(String UserName, int Access) {
        initComponents();
        lblLoggedInAs.setText("Logged in as: " + UserName);
        accessLevel = Access;     
        this.getContentPane().setBackground(Color.DARK_GRAY);
       checkTime();
    }
    
           String url;
    Connection con = null;
    Statement stmt = null;
    int numRecords;
    POS.Operations operations = new POS.Operations();
        

     public void openDatabase () {
        url = "jdbc:ucanaccess://C:/Users/user/Desktop/POS/PosDatabase.accdb";
        try{
          con = DriverManager.getConnection(url);        
          stmt = con.createStatement();
            System.out.println("Connected");
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public void closeDatabase (){
        try{
            stmt.close();
            con.close();
            System.out.println("Closed");
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTotalPrice = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn6 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btnBackspace = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btnNextMenu = new javax.swing.JButton();
        btnSUPVMenu = new javax.swing.JButton();
        btnCheckAuthorisation = new javax.swing.JButton();
        btnMenuButton3 = new javax.swing.JButton();
        btnCancelItem = new javax.swing.JButton();
        txtLogOff = new javax.swing.JButton();
        btnAddItemFromList = new javax.swing.JButton();
        lblLoggedInAs = new javax.swing.JLabel();
        lblDateTime = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstProducts = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPrices = new javax.swing.JList<>();
        btnMenuButton5 = new javax.swing.JButton();
        btnMenuButton7 = new javax.swing.JButton();
        btnMenuButton8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(0, 0, 255));
        lblTotalPrice.setText("$0.00");

        txtCode.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtCode.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCode.setEnabled(false);
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        btnEnter.setBackground(new java.awt.Color(0, 255, 0));
        btnEnter.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEnter.setText("ENTER");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTotalPrice)
                        .addGap(38, 38, 38))))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btn6.setBackground(new java.awt.Color(255, 255, 255));
        btn6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(255, 0, 0));
        btnClear.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("C");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(255, 255, 255));
        btn3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(255, 255, 255));
        btn0.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(255, 255, 255));
        btn5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(255, 255, 255));
        btn4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btnBackspace.setBackground(new java.awt.Color(255, 255, 255));
        btnBackspace.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btnBackspace.setText("<");
        btnBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackspaceActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(255, 255, 255));
        btn7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(255, 255, 255));
        btn8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(255, 255, 255));
        btn9.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn1.setBackground(new java.awt.Color(255, 255, 255));
        btn1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(255, 255, 255));
        btn2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(btn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBackspace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        btnNextMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnNextMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Downloads\\arrow.png")); // NOI18N

        btnSUPVMenu.setBackground(new java.awt.Color(255, 255, 255));
        btnSUPVMenu.setText("SUPERVISOR MENU");
        btnSUPVMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSUPVMenuActionPerformed(evt);
            }
        });

        btnCheckAuthorisation.setBackground(new java.awt.Color(255, 255, 255));
        btnCheckAuthorisation.setText("CHECK AUTHORISATION");
        btnCheckAuthorisation.setEnabled(false);
        btnCheckAuthorisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckAuthorisationActionPerformed(evt);
            }
        });

        btnMenuButton3.setBackground(new java.awt.Color(255, 255, 255));

        btnCancelItem.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelItem.setText("CANCEL ITEM");
        btnCancelItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelItemActionPerformed(evt);
            }
        });

        txtLogOff.setBackground(new java.awt.Color(255, 255, 255));
        txtLogOff.setText("LOG OFF");
        txtLogOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogOffActionPerformed(evt);
            }
        });

        btnAddItemFromList.setBackground(new java.awt.Color(255, 255, 255));
        btnAddItemFromList.setText("ADD ITEM FROM LIST");
        btnAddItemFromList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemFromListActionPerformed(evt);
            }
        });

        lblLoggedInAs.setForeground(new java.awt.Color(255, 255, 255));
        lblLoggedInAs.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblDateTime.setForeground(new java.awt.Color(255, 255, 255));
        lblDateTime.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lstProducts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lstProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstProductsMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstProducts);

        lstPrices.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lstPrices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstPricesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstPrices);

        btnMenuButton5.setBackground(new java.awt.Color(255, 255, 255));

        btnMenuButton7.setBackground(new java.awt.Color(255, 255, 255));

        btnMenuButton8.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblLoggedInAs, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnMenuButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddItemFromList, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnMenuButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCancelItem, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLogOff, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnCheckAuthorisation, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnMenuButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMenuButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSUPVMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnNextMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddItemFromList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLogOff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenuButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCheckAuthorisation, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancelItem, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenuButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnMenuButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSUPVMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNextMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane3))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblLoggedInAs, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        txtCode.setText(txtCode.getText() + "1");
        checkTime();
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        txtCode.setText(txtCode.getText() + "2");
        checkTime();
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtCode.setText(txtCode.getText() + "3");
        checkTime();
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        txtCode.setText(txtCode.getText() + "4");
        checkTime();
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        txtCode.setText(txtCode.getText() + "5");
        checkTime();
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        txtCode.setText(txtCode.getText() + "6");
        checkTime();
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        txtCode.setText(txtCode.getText() + "7");
        checkTime();
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        txtCode.setText(txtCode.getText() + "8");
        checkTime();
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        txtCode.setText(txtCode.getText() + "9");
        checkTime();
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackspaceActionPerformed
        if (!txtCode.getText().equals("")){
        txtCode.setText(txtCode.getText().substring(0, txtCode.getText ().length() - 1));
        checkTime();
        }
    }//GEN-LAST:event_btnBackspaceActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtCode.setText("");
        checkTime();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        txtCode.setText(txtCode.getText() + "0");
        checkTime();
    }//GEN-LAST:event_btn0ActionPerformed

    private void txtLogOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogOffActionPerformed
        loginScreen login = new loginScreen();
        login.pack();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtLogOffActionPerformed

    private void btnSUPVMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSUPVMenuActionPerformed
        // Supervisor reason codes are: SUPV Menu = 1; Restricted Item = 2
        if(accessLevel == 1 || accessLevel ==2){
            SupervisorMenu SupvMenu = new SupervisorMenu();
            SupvMenu.pack();
            SupvMenu.setLocationRelativeTo(null);
            SupvMenu.setVisible(true);
        }
        else {
            SupervisorIntervention supvIntervention = new SupervisorIntervention(1, this);
            supvIntervention.pack();
            supvIntervention.setLocationRelativeTo(null);
            supvIntervention.setVisible(true);
        }
    }//GEN-LAST:event_btnSUPVMenuActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        checkTime();
        if (!txtCode.getText().equals("")){
        DecimalFormat df = new DecimalFormat("#.00");
        openDatabase();
        String query = "SELECT * FROM Products WHERE Barcode = '" + txtCode.getText() + "'";
        try{
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            if (rs.next()){ 
                if(!rs.getString(8).equals("1")){
                    if(rs.getString(7).equals("1")){
                        if(accessLevel == 3){
                            if(transactionAuthorised == false){
                            codeOnHold = rs.getInt(4);
                            SupervisorIntervention supvIntervention = new SupervisorIntervention(2, this);
                            supvIntervention.pack();
                            supvIntervention.setLocationRelativeTo(null);
                            supvIntervention.setVisible(true);                            
                            btnCheckAuthorisation.setEnabled(true);
                            txtCode.setText("");
                            return;
                            }
                        }
                        else{
                            if (transactionAuthorised == false){
                             javax.swing.JOptionPane.showMessageDialog(this, "Restricted Item Check Age", "ALERT", javax.swing.JOptionPane.WARNING_MESSAGE);
                             transactionAuthorised = true;
                        }
                        }
                    }
                double price = rs.getDouble(5);
                double promotion = 0;
                double promoDiscount = 0;
                productListModel.addElement(rs.getString(2));
                priceListModel.addElement("$" + df.format(price));
                lstProducts.setModel(productListModel);
                lstPrices.setModel(priceListModel);
                String test = rs.getString(5);
                if (!rs.getString(6).equals("0.0000")){
                    promotion = rs.getDouble(6);
                    promoDiscount = (price - promotion);
                    productListModel.addElement("      ON PROMOTION");
                    priceListModel.addElement("-$" + df.format(promoDiscount));
                    lstProducts.setModel(productListModel);
                    lstPrices.setModel(priceListModel);
                }
                totalPrice = totalPrice + price - promoDiscount;
                String stringPrice = df.format(totalPrice);
                lblTotalPrice.setText("$" + stringPrice);

                txtCode.setText("");
            }
                else{
                    javax.swing.JOptionPane.showMessageDialog(this, "Item Sale Prohibited", "Do Not Sell", javax.swing.JOptionPane.ERROR_MESSAGE);
                    txtCode.setText("");
                }
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Item not found", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                txtCode.setText("");
            }
        }
        catch (Exception e){
            e.printStackTrace();
        }
        closeDatabase();
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnCheckAuthorisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckAuthorisationActionPerformed
        if (transactionAuthorised == true){
            txtCode.setText(String.valueOf(codeOnHold));
            javax.swing.JOptionPane.showMessageDialog(this, "Press Enter Again to insert into transaction", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            codeOnHold = 0;
            btnCheckAuthorisation.setEnabled(false);
            
        }
        else{
            javax.swing.JOptionPane.showMessageDialog(this, "Transaction not authorised", "Message", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            codeOnHold = 0;
            btnCheckAuthorisation.setEnabled(false);
            
        }
    }//GEN-LAST:event_btnCheckAuthorisationActionPerformed

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void btnCancelItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelItemActionPerformed
        DecimalFormat df = new DecimalFormat("#.00");
        int selectedItem = lstProducts.getSelectedIndex();
        lstPrices.setSelectedIndex(selectedItem);
        double price = Double.parseDouble(lstPrices.getSelectedValue().substring(1));
        lstProducts.setSelectedIndex(selectedItem + 1);
        if (lstProducts.getSelectedValue().equals("      ON Promotion")){
            productListModel.removeElementAt(selectedItem);
            priceListModel.removeElementAt(lstProducts.getSelectedIndex());
        }
        else{
            lstProducts.setSelectedIndex(selectedItem - 1);
        }
        productListModel.removeElementAt(selectedItem);
        priceListModel.removeElementAt(selectedItem);
        lstProducts.setModel(productListModel);
        lstPrices.setModel(priceListModel);
        totalPrice = totalPrice - price;
        String stringPrice = df.format(totalPrice);
        lblTotalPrice.setText("$" + stringPrice);
        
    }//GEN-LAST:event_btnCancelItemActionPerformed

    private void btnAddItemFromListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemFromListActionPerformed
        AddItemMenu aim = new AddItemMenu(this);
        aim.pack();
        aim.setLocationRelativeTo(null);
        aim.setVisible(true);
    }//GEN-LAST:event_btnAddItemFromListActionPerformed

    private void lstProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProductsMouseClicked
        lstPrices.setSelectedIndex(lstProducts.getSelectedIndex());
    }//GEN-LAST:event_lstProductsMouseClicked

    private void lstPricesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstPricesMouseClicked
        lstProducts.setSelectedIndex(lstPrices.getSelectedIndex());
    }//GEN-LAST:event_lstPricesMouseClicked

    private void checkTime(){
                DateFormat df = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        Calendar calobj = Calendar.getInstance();
        lblDateTime.setText(df.format(calobj.getTime()));         
    }
    
    public void addFromMenu(int code){
        checkTime();
       
        DecimalFormat df = new DecimalFormat("#.00");
        openDatabase();
        String query = "SELECT * FROM Products WHERE ItemNum = '" + code + "'";
        try{
            PreparedStatement pst = con.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            if (rs.next()){ 
                if(!rs.getString(8).equals("1")){
                    if(rs.getString(7).equals("1")){
                        if(accessLevel == 3){
                            if(transactionAuthorised == false){
                            codeOnHold = rs.getInt(3);
                            SupervisorIntervention supvIntervention = new SupervisorIntervention(2, this);
                            supvIntervention.pack();
                            supvIntervention.setLocationRelativeTo(null);
                            supvIntervention.setVisible(true);                            
                            btnCheckAuthorisation.setEnabled(true);
                            txtCode.setText("");
                            return;
                            }
                        }
                        else{
                            if (transactionAuthorised == false){
                             javax.swing.JOptionPane.showMessageDialog(this, "Restricted Item Check Age", "ALERT", javax.swing.JOptionPane.WARNING_MESSAGE);
                             transactionAuthorised = true;
                        }
                        }
                    }
                double price = rs.getDouble(5);
                double promotion = 0;
                double promoDiscount = 0;
                productListModel.addElement(rs.getString(2));
                priceListModel.addElement("$" + df.format(price));
                lstProducts.setModel(productListModel);
                lstPrices.setModel(priceListModel);
                String test = rs.getString(5);
                if (!rs.getString(6).equals("0.0000")){
                    promotion = rs.getDouble(6);
                    promoDiscount = (price - promotion);
                    productListModel.addElement("      ON PROMOTION");
                    priceListModel.addElement("-$" + df.format(promoDiscount));
                    lstProducts.setModel(productListModel);
                    lstPrices.setModel(priceListModel);
                }
                totalPrice = totalPrice + price - promoDiscount;
                String stringPrice = df.format(totalPrice);
                lblTotalPrice.setText("$" + stringPrice);

                txtCode.setText("");
            }
                else{
                    javax.swing.JOptionPane.showMessageDialog(this, "Item Sale Prohibited", "Do Not Sell", javax.swing.JOptionPane.ERROR_MESSAGE);
                    txtCode.setText("");
                }
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(this, "Item not found", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                txtCode.setText("");
            }
        }
        catch (Exception e){
            e.printStackTrace();
        }
        closeDatabase();
        
                                       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POSFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POSFrame(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAddItemFromList;
    private javax.swing.JButton btnBackspace;
    private javax.swing.JButton btnCancelItem;
    private javax.swing.JButton btnCheckAuthorisation;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnMenuButton3;
    private javax.swing.JButton btnMenuButton5;
    private javax.swing.JButton btnMenuButton7;
    private javax.swing.JButton btnMenuButton8;
    private javax.swing.JButton btnNextMenu;
    private javax.swing.JButton btnSUPVMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblDateTime;
    private javax.swing.JLabel lblLoggedInAs;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JList<String> lstPrices;
    private javax.swing.JList<String> lstProducts;
    private javax.swing.JTextField txtCode;
    private javax.swing.JButton txtLogOff;
    // End of variables declaration//GEN-END:variables
}
